In [36]:
import numpy
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn import tree
from sklearn.datasets import load_iris

In [37]:
iris_data=load_iris()

In [38]:
iris_data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [39]:
iris_data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [40]:
 X_train, X_test, y_train, y_test =train_test_split(iris_data.data,iris_data.target,test_size=0.3)

In [41]:
len(X_train)

105

In [42]:
lr=LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9777777777777777

In [43]:
dt=tree.DecisionTreeClassifier()
dt.fit(X_train,y_train)
dt.score(X_test,y_test)

0.9777777777777777

In [44]:
svm=SVC(gamma='auto')
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9777777777777777

In [45]:
rfc=RandomForestClassifier()
rfc.fit(X_train,y_train)
rfc.score(X_test,y_test)

0.9777777777777777

In [46]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=5)
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [47]:
def get_score(model,X_train,y_train,X_test,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [48]:
get_score(SVC(gamma='auto'),X_train,y_train,X_test,y_test)

0.9777777777777777

In [49]:
get_score(LogisticRegression(),X_train,y_train,X_test,y_test)

0.9777777777777777

In [50]:
for train_index,test_index in kf.split(iris_data.data):
    print(train_index,test_index)

[ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47
  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 1

In [51]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=5)
score_lr=[]
score_svm =[]
score_rfc=[]
for train_index,test_index in folds.split(iris_data.data,iris_data.target):
    X_train, X_test, y_train, y_test = iris_data.data[train_index], iris_data.data[test_index],iris_data.target[train_index], iris_data.target[test_index]
    score_svm.append(get_score(SVC(gamma='auto'), X_train, y_train,X_test,y_test))
    score_rfc.append(get_score(RandomForestClassifier(), X_train, y_train,X_test ,y_test))
    score_lr.append(get_score(LogisticRegression(), X_train, y_train,X_test, y_test))  
    

C:\Users\Krishna Mohan Singh\New folder (3)\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [52]:
score_svm

[0.9666666666666667, 1.0, 0.9666666666666667, 0.9666666666666667, 1.0]

In [53]:
score_rfc

[0.9666666666666667,
 0.9666666666666667,
 0.9333333333333333,
 0.9666666666666667,
 1.0]

In [54]:
score_lr

[0.9666666666666667, 1.0, 0.9333333333333333, 0.9666666666666667, 1.0]

In [55]:
from sklearn.model_selection import cross_val_score

In [56]:
cross_val_score(LogisticRegression(),iris_data.data,iris_data.target,cv=3)

C:\Users\Krishna Mohan Singh\New folder (3)\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.98, 0.96, 0.98])

In [57]:
cross_val_score(SVC(gamma='auto'),iris_data.data,iris_data.target,cv=3)

array([0.98, 0.98, 0.96])

In [58]:
cross_val_score(RandomForestClassifier(n_estimators=40),iris_data.data,iris_data.target,cv=3)

array([0.98, 0.94, 0.96])